e_commerce/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
"""Defines URL patterns for store."""

from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='store/login_form.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/', views.profile, name='profile'),
    path('cart/', views.cart, name='cart'),
    path('view/<int:product_id>/', views.view, name='view'),
    path('checkout/', views.check_out, name='checkout'),
    path('update_item/', views.update_item, name='update_item'),
    path('process_order/', views.process_order, name='process_order'),
    path('buy_now/<str:product_id>/<str:qty>', views.buy_now, name='buy_now'),
    path('process_order_now/', views.process_order_now, name='process_order_now'),
    path('product/create/', views.ProductCreate.as_view(), name='product_create'),
]

store/models.py
"""Models for store"""

from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Product(models.Model):
    """A model representing a product."""
    name = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    digital = models.BooleanField(default=False, null=True, blank=False)
    image = models.ImageField(null=True, blank=True)
    description = models.TextField(null=True)

    def get_absolute_url(self):
        """Once a user uploads a new product."""
        return reverse('store:view', args=[str(self.id)])

    def __str__(self):
        return self.name

    @property
    def image_url(self):
        """A decorator to fix for missing images url error while rendering index page."""
        try:
            url = self.image.url
        except:
            url = ''
        return url


class Review(models.Model):
    """A model for reviews of a product."""
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, blank=True, null=True)
    reviewer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    review = models.TextField()
    date_added = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.review


class Order(models.Model):
    """A model representing an order/cart."""
    user = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False, null=True, blank=False)
    transaction_id = models.CharField(max_length=200, null=True)

    def __str__(self):
        return str(self.id)

    @property
    def shipping(self):
        """Whether shipping is required based on digital."""
        shipping = False
        order_items = self.orderitem_set.all()
        for item in order_items:
            if item.product.digital == False:
                shipping = True
        return shipping

    @property
    def get_cart_total(self):
        """Get total of all item's price in order/cart."""
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

    @property
    def get_cart_items(self):
        """Get total number of items in order/cart."""
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total


class OrderItem(models.Model):
    """A model representing an item in an order/cart."""
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, blank=True, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    quantity = models.IntegerField(default=0, blank=True, null=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.product.name

    @property
    def get_total(self):
        """Return the total of our order."""
        total = self.product.price * self.quantity
        return total


class ShippingAddress(models.Model):
    """A model representing a shipping address."""
    user = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    address = models.CharField(max_length=200, null=True)
    city = models.CharField(max_length=200, null=True)
    state = models.CharField(max_length=200, null=True)
    zipcode = models.CharField(max_length=200, null=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.address
    
    class Meta:
        verbose_name_plural = "Shipping addresses"
        

store/forms.py
"""A module for all django forms."""
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class ReviewForm(forms.Form):
    """Form for product review."""
    review = forms.CharField(label="", widget=forms.Textarea)


class RegisterForm(UserCreationForm):
    """Create a new user."""
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ('username', 'email')

    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)

        for fieldname in ['username', 'password1', 'password2']:
            self.fields[fieldname].help_text = None
    

store/views.py
"""Views page for store app."""
import json
import datetime

from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.http import JsonResponse, HttpResponseRedirect
from django.urls import reverse
from django.views.generic import CreateView
from django.contrib.auth.models import User
from django.views.decorators.csrf import ensure_csrf_cookie

from .models import Product, Order, OrderItem, ShippingAddress, Review
from .utils import cart_data, guest_order
from .forms import ReviewForm, RegisterForm

# Create your views here.
@ensure_csrf_cookie
def index(request):
    """The home page for our Ecom site."""
    data = cart_data(request)
    cart_items = data['cartItems']  

    products = Product.objects.all()
    context = {'products': products, 'cartItems': cart_items}
    return render(request, 'store/index.html', context)


def view(request, product_id):
    """When user clicks view button for a particular item."""
    product = Product.objects.get(id=product_id)
    if request.method == 'POST':
        # Take in the data the user submitted and save it as form
        form = ReviewForm(request.POST)

        # Check if form data is valid (server-side)
        if form.is_valid():
            # Isolate the user review from the 'cleaned' version of form data
            review = form.cleaned_data['review']
            reviewer = request.user

            # See if the user has already given a review for the product
            try:
                # If so only edit the review
                edit_review = Review.objects.get(product=product, reviewer=reviewer)
                edit_review.review = review
                edit_review.save()
            except:
                # Else create a new review for the product with that user
                new_review = Review.objects.create(
                    product=product,
                    reviewer=reviewer,
                    review=review
                )
                new_review.save()
            return HttpResponseRedirect(reverse('store:view', args=[product_id]))
    
    data = cart_data(request)
    items = data['items']
    cart_items = data['cartItems']
    form = ReviewForm()
    reviews = Review.objects.filter(product=product).all()
    for review in reviews:
        if review.reviewer == request.user:
            review = Review.objects.get(product=product, reviewer=request.user)
            form = ReviewForm(initial={'review': review})
    if len(reviews) == 1:
        reviews_count = "1 review"
    else:
        reviews_count = f"{len(reviews)} reviews"

    context = {
        'product': product,
        'items': items,
        'cartItems': cart_items,
        'form': form,
        'reviews': reviews,
        'reviews_count': reviews_count
        }
    return render(request, 'store/view.html', context)


def cart(request):
    """When user adds an item to cart."""
    data = cart_data(request)
    items = data['items']
    order = data['order']
    cart_items = data['cartItems']

    context = {'items': items, 'order': order, 'cartItems': cart_items}
    return render(request, 'store/cart.html', context)


def check_out(request):
    """When user wants to checkout cart items."""
    data = cart_data(request)
    items = data['items']
    order = data['order']
    cart_items = data['cartItems']

    context = {'items': items, 'order': order, 'cartItems': cart_items}
    return render(request, 'store/checkout.html', context)


def update_item(request):
    """Update item in cart."""
    data = json.loads(request.body)
    product_id = data['productId']

    try:
        action = data['action']
    except KeyError:
        action = ''

    try:
        qty = data['qty']
    except KeyError:
        qty = ''

    product = Product.objects.get(id=product_id)
    order, created = Order.objects.get_or_create(user=request.user, complete=False)
    order_item, created = OrderItem.objects.get_or_create(order=order, product=product)

    if action != '':
        if action == 'add':
            order_item.quantity = (order_item.quantity + 1)
        elif action == 'remove':
            order_item.quantity = (order_item.quantity - 1)
    else:
        order_item.quantity += qty

    order_item.save()

    if order_item.quantity <= 0:
        order_item.delete()

    return JsonResponse('Item was added', safe=False)


def process_order(request):
    """When user makes a payment."""
    transaction_id = datetime.datetime.now().timestamp()
    data = json.loads(request.body)

    if request.user.is_authenticated:
        user = request.user
        order, created = Order.objects.get_or_create(user=request.user, complete=False)
    else:
        user, order = guest_order(request, data)

    total = float(data['form']['total'])
    order.transaction_id = transaction_id

    if total == order.get_cart_total:
        order.complete = True
    order.save()

    if order.shipping == True:
        ShippingAddress.objects.create(
            user= user,
            order=order,
            address=data['shipping']['address'],
            city=data['shipping']['city'],
            state=data['shipping']['state'],
            zipcode=data['shipping']['zipcode']
        )

    return JsonResponse('Payment complete!', safe=False)


def buy_now(request, product_id, qty):
    """When user clicks on 'buy now' button."""
    data = cart_data(request)
    cart_items = data['cartItems']

    product = Product.objects.get(id=product_id)
    # If product is digital, then shipping is False
    shipping = not product.digital
    total = product.price * int(qty)
    context = {
        'product': product,
        'shipping': shipping,
        'cartItems': cart_items,
        'qty': qty,
        'total': total
        }

    return render(request, 'store/buy_now.html', context)


def process_order_now(request):
    """When a user clicks 'buy now'."""
    transaction_id = datetime.datetime.now().timestamp()
    data = json.loads(request.body)

    if request.user.is_authenticated:
        user = request.user
    else:
        # Creating a guest customer using the data received from the fetch API
        user, created = User.objects.get_or_create(
            username=data['form']['name'],
            email=data['form']['email']
            )
        user.save()

    order = Order(user=user, complete=True, transaction_id=transaction_id)
    order.save()   
    # Check if we need to save shipping Info
    if data['shipping']['address'] != None:
        ShippingAddress.objects.create(
            user=user,
            order=order,
            address=data['shipping']['address'],
            city=data['shipping']['city'],
            state=data['shipping']['state'],
            zipcode=data['shipping']['zipcode']
        )
    return JsonResponse('Payment complete!', safe=False)


class ProductCreate(CreateView):
    """A create view to let users upload a product."""
    model = Product
    fields = ['name', 'price', 'digital', 'image', 'description']


def register(request):
    """A view to register new users."""
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('store:index')
    else:
        form = RegisterForm()
    return render(request, 'store/registration_form.html', {'form': form})


def profile(request):
    """Display user profile."""
    data = cart_data(request)
    cart_items = data['cartItems']
    return render(request, 'store/profile.html', {'cartItems': cart_items})

store/templates/store/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <!-- Custom CSS -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'store/css/main.css' %}">

    <title>
      Ecom - 
      {% block title %}
        Home
      {% endblock title%}
    </title>


    <script>
      var user = '{{request.user}}'

      // Code fix pasted from Django csrf token ajax
      function getToken(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
          const cookies = document.cookie.split(';');
          for (let i = 0; i < cookies.length; i++) {
            const cookie = cookies[i].trim();
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
              cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
              break;
            }
          }
        }
        return cookieValue;
      }
      var csrftoken = getToken('csrftoken');
      console.log('CSRF', csrftoken)

      function getCookie(name){
        // Split cookie string and get all individual name=value pairs in an array
        var cookieArr = document.cookie.split(";")

        // Loop through the array elements
        for(var i=0; i < cookieArr.length;i++){
          var cookiePair = cookieArr[i].split("=")

          // Removing whitespace at the beginning of the cookie name and compare it with the given string 
          if(name == cookiePair[0].trim()){
            // Decode the cookie value and return
            return decodeURIComponent(cookiePair[1])
          }
        }

        // Return null if not found
        return null
      }

      var cart = JSON.parse(getCookie('cart'))
      if(cart == undefined){
        cart = {}
        document.cookie = 'cart=' + JSON.stringify(cart) + ";domain=;path=/"
      }
    </script>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-2">
        <a class="navbar-brand" href="{% url 'store:index' %}">Ecom</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'store:profile' %}">Hi, {{ user.username }}</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'store:logout' %}">Log out</a>
              </li> 
            {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'store:register' %}">Register</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'store:login' %}">Sign in</a>
              </li>
            {% endif %}
            <li class="nav-item" id='cart'>
              <div class="form-inline">
                <a href="{% url 'store:cart' %}">
                  <img id="cart-icon" src="{% static 'store/images/cart.png' %}" alt="cart">
               </a>
               <p id="cart-total">{{cartItems}}</p>
              </div>
            </li>
          </ul>
        </div>
    </nav>

    <div class="container-fluid">
      {% block content %}
      
      {% endblock content %}
    </div>

    
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

    <!-- Optional JavaScript -->
    <script type="text/javascript" src="{% static 'store/js/cart.js'%}"></script>
  </body>
</html>

store/templates/store/buy_now.html
{% extends 'store/base.html' %}
{% block title %}
    Buy {{product}}
{% endblock title%}

{% block content %}
<div class="row">
    <div class="col-lg-6">
        <div class="box-element" id="form-wrapper">
            <form action="" id="form">
                {% if not request.user.is_authenticated %}
                    <div id="user-info">
                        <div class="form-field">
                            <input class="form-control" type="text" name="name" id="" placeholder="Name.." required>
                        </div>
                        <div class="form-field">
                            <input class="form-control" type="email" name="email" placeholder="Email.." required>
                        </div>
                    </div>
                    <hr>
                {% endif %}
                
                {% if shipping %}
                    <div id="shipping-info">
                        <p>Shipping Information:</p>
                        <hr>
                        <div class="form-field">
                            <input class="form-control" type="text" name="address" id="" placeholder="Address..">
                        </div>
                        <div class="form-field">
                            <input class="form-control" type="text" name="city" id="" placeholder="City..">
                        </div>
                        <div class="form-field">
                            <input class="form-control" type="text" name="state" id="" placeholder="State..">
                        </div>
                        <div class="form-field">
                            <input class="form-control" type="text" name="zipcode" id="" placeholder="Zip code..">
                        </div>
                        <div class="form-field">
                            <input class="form-control" type="text" name="country" id="" placeholder="Country..">
                        </div>
                    </div>
                    <hr>
                {% endif %}
                <input id="form-button" class="btn btn-success btn-block" type="submit" value="Continue">
            </form>
        </div>
        <br>

        <div class="box-element hidden" id="payment-info">
            <p>Paypal Options</p>

            <!-- Set up a container element for the button -->
            <div id="paypal-button-container"></div>
        </div>
    </div>

    <div class="col-lg-6">
        <div class="box-element">
            <a class="btn btn-outline-dark" href="{% url 'store:cart' %}">&#x2190; Back to Cart</a>
            <hr>
            <h3>Order Summary</h3>
            <hr>
            <div class="cart-row">
                <div class="flex-2"><img class="row-image default" src="{{product.image_url}}" alt="{{item.product}}"></div>
                <div class="flex-2"><p>{{product.name}}</p></div>
                <div class="flex-1"><p>${{product.price}}</p></div>
                <div class="flex-1"><p>x{{qty}}</p></div>
            </div>
            <h5>Total: ${{total}}</h5>
        </div>
    </div>
</div>

    <!-- Include the PayPal JavaScript SDK -->
    <script src="https://www.paypal.com/sdk/js?client-id=AdolZR0tFJ7-AC1eZrGAZoN0KO2ALbKwG4YHUFX-WULO71TzvnxY8W1gPxG51FbVwlHiyq_LlF-krBcN&currency=USD&disable-funding=credit"></script>

    <script>
        var total = '{{total}}'

        // Render the PayPal button into #paypal-button-container
        paypal.Buttons({

            style:{
                color:'blue',
                height:40,
            },

            // Set up the transaction
            createOrder: function(data, actions) {
                return actions.order.create({
                    purchase_units: [{
                        amount: {
                            value: parseFloat(total).toFixed(2)
                        }
                    }]
                });
            },

            // Finalize the transaction
            onApprove: function(data, actions) {
                return actions.order.capture().then(function(details) {
                    // Show a success message to the buyer
                    // alert('Transaction completed by ' + details.payer.name.given_name + '!');
                    submitFormData()
                });
            }


        }).render('#paypal-button-container');
    </script>

    <script>
        var shipping = '{{shipping}}'

        if(shipping == 'False' && user != 'AnonymousUser'){
            document.getElementById('form-wrapper').classList.add('hidden')
            document.getElementById('payment-info').classList.remove('hidden')
        }

        var form = document.getElementById('form')

        form.addEventListener('submit', function(e){
            e.preventDefault()
            document.getElementById('form-button').classList.add('hidden')
            document.getElementById('payment-info').classList.remove('hidden')
        })


        function submitFormData(){

            var userFormData = {
                'name': null,
                'email':null,
                'total':total
            }

            var shippingInfo = {
                'address':null,
                'city':null,
                'state':null,
                'zipcode':null,
            }

            if(shipping != 'False'){
                shippingInfo.address = form.address.value
                shippingInfo.city = form.city.value
                shippingInfo.state = form.state.value
                shippingInfo.zipcode = form.zipcode.value
            }

            if(user == 'AnonymousUser'){
                userFormData.name = form.name.value
                userFormData.email = form.email.value
            }

            var url = '/process_order_now/'
            fetch(url,{
                method:'POST',
                headers: {
                    'Content-Type':'application/json',
                    'X-CSRFToken':csrftoken,
                },
                body:JSON.stringify({'form':userFormData, 'shipping':shippingInfo})
            })

            .then((response) => response.json())
            .then((data) => {
                alert('Transaction completed')

                document.cookie = 'cart=' + JSON.stringify(cart) + ";dommain=;path=/"
                window.location.href = "{% url 'store:index' %}"
            })
        }
    </script>
{% endblock content %}

store/templates/store/cart.html
{% extends 'store/base.html' %}
{% load static %}

{% block title %}
    Cart
{% endblock title%}

{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <div class="box-element">
                <a class="btn btn-outline-dark" href="{% url 'store:index' %}">&#x2190; Continue Shopping</a>
                
                <br>
                <br>

                <table class="table">
                    <tr>
                        <th><h5>Items: <strong>{{order.get_cart_items}}</strong></h5></th>
                        <th><h5>Total: <strong>${{order.get_cart_total}}</strong></h5></th>
                        <th>
                            <a class="btn btn-success right" href="{% url 'store:checkout' %}">Checkout</a>
                        </th>
                    </tr>
                </table>
            </div>

            <br>

            <div class="box-element">
                <div class="cart-row">
                    <div class="flex-2"></div>
                    <div class="flex-2"><strong>Item</strong></div>
                    <div class="flex-1"><strong>Price</strong></div>
                    <div class="flex-1"><strong>Quantity</strong></div>
                    <div class="flex-1"><strong>Total</strong></div>
                </div>

                {% for item in items %}
                    <div class="cart-row">
                        <div class="flex-2"><img class="row-image" src="{{item.product.image_url}}" alt="{{item.product}}"></div>
                        <div class="flex-2">{{item.product.name}}</div>
                        <div class="flex-1">${{item.product.price}}</div>
                        <div class="flex-1">
                            <p class="quantity">{{item.quantity}}</p>
                            <div class="quantity">
                                <img data-product={{item.product.id}} data-action="add" class="chg-quantity update-cart" src="{% static 'store/images/arrow-up.png' %}" alt="arrow-up">
                                <img data-product={{item.product.id}} data-action="remove" class="chg-quantity update-cart" src="{% static 'store/images/arrow-down.png' %}" alt="arrow-down">
                            </div>
                        </div>
                        <div class="flex-1">${{item.get_total}}</div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock content %}

store/templates/store/form-template.html
{% load bootstrap4 %}
{% for field in form %}
    <div>{% bootstrap_field field %}</div>
{% endfor %}

<Script>
    console.log('hi')
    // Hide the cart icon in the navbar
    document.getElementById('cart').innerHTML = '';
</Script>

store/templates/store/index.html
{% extends 'store/base.html' %}
{% load static %}

{% block content %}
<div class="row">
  {% for product in products %}
    <a href="{% url 'store:view' product.id %}" class="a-div">
      <div class="col-lg-3 col-md-4 col-6 product">
        <img class="thumbnail" src="{{ product.image_url }}" alt="{{ product }}">
        <div class="box-element">
          <h6 class="product-name"><strong>{{ product.name }}</strong></h6>
          <hr>
          <h5>${{ product.price }}</h5> 
    </a>
          <button data-product="{{product.id}}" data-action="add" class="btn btn-warning btn-block update-cart">Add to cart</button>
        </div>
      </div>
  
  {% empty %}
    <h3>Nothing here!</h3>
  {% endfor %}
</div>
{% endblock content %}

store/templates/store/login_form.html
{% extends 'store/base.html' %}

{% block title %}
    Login
{% endblock title %}

{% block content %}


<div class="box-element center">
    {% if form.errors %}
        <div class="alert alert-danger">
            Your username and password didn't match. Please try again.
        </div>
    {% endif %}
    <form action="" method="POST">
        {% csrf_token %} 
        {% include 'store/form-template.html' %}
        <button type="submit" class="btn btn-success">Submit</button>
    </form>
</div>
{% endblock content %}

store/templates/store/product_form.html
{% extends 'store/base.html' %}

{% block title %}
    Upload product
{% endblock title %}

{% block content %}
<div class="box-element center">
    <h4>Enter product details:</h4>
    <hr>
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %} 
        {% include 'store/form-template.html' %}
        <button type="submit" class="btn btn-success">Submit</button>
    </form>
</div>
{% endblock content %}

store/templates/store/profile.html
{% extends 'store/base.html' %}

{% block title %}
    Profile
{% endblock title %}

{% block content %}
    <div class="box-element center">
        <p>Username: {{user.username}}</p>
        <p>
            Email:
            {% if user.email %}
                {{ user.email }}
            {% else %}
                None
            {% endif %}
        </p>
        <p>Upload a product: <a href="{% url 'store:product_create' %}">Click Here!</a></p>
    </div>
     
{% endblock content %}

store/templates/store/registration_form.html
{% extends 'store/base.html' %}

{% block title %}
    Register
{% endblock title %}

{% block content %}
<div class="box-element center">
    <form action="" method="POST">
        {% csrf_token %} 
        {% include 'store/form-template.html' %}
        <button type="submit" class="btn btn-success">Submit</button>
    </form>
</div>
{% endblock content %}